### ISSUE TITLE
Incomplete forms are allowed to be submitted

### ISSUE THREAD

**Issue by mmperry** [cims-bioko/cims-tablet#277] opened 2018-08-27 16:02 UTC
Users are able to mark incomplete forms as complete, and send the incomplete forms to the server.  This is causing an error when exporting data from briefcase.  While the solution is not needed immediately, the compete data is needed for forms that are unable to be exported from brief  within the next two weeks.  Attached is the spreadsheet of the incomplete instances  (highlighted in yellow) and the data collected in the same submission as the incomplete instances. Note:  this is not a complete list, please request if needed. 

  
[SurveyErrorInformation20Aug2018.xlsx](https://github.com/cims-bioko/cims-tablet/files/2324641/SurveyErrorInformation20Aug2018.xlsx)

**Comment by batkinson** [comment] 2018-08-28 09:01
When launching a new form, this application generates a new xml instance by using  `OdkCollectHelper.registerInstance(...)`. That code uses the content provider api's `insert` method with a URL that is ultimately handled by ODK Collect's `InstanceProvider`, which sets the status to 'incomplete' when not provided in the supplied content values: https://github.com/opendatakit/collect/blob/be35e967277148ec4cb3ccadfe2c46ef16206e42/collect_app/src/main/java/org/odk/collect/android/provider/InstanceProvider.java#L161

**Comment by batkinson** [comment] 2018-08-28 11:39
Looking through the this application's handling of instance status, the only place status is used (set) directly is when approving "forms requiring review", and similarly when attempting to submit forms so that forms requiring approval aren't submitted by Collect until they are approved. The only place where status is set to "complete" is in `ChecklistFragment.approveForm(...)`, which requires user intervention. the only place where the status is set to "incomplete" is in `SupervisorActivity.sendApprovedForms`, where instances flagged as requiring review in their content are marked incomplete before launching ODK Collect. The "submitted" status is only used in `FormInstance` to allow pruning hierarchy links to sent forms, and for determining editability to block editing encrypted forms and showing them as locked. There were no other typed references to `InstanceProviderAPI.InstanceColumns.STATUS` and other references to 'status' were related to other concepts like individuals, etc.

This suggests that there is something going wrong in Collect, since forms are generated with the default status, which is "incomplete", and unless users are able to and are in fact approving incomplete forms using the app's approval functionality (which would only work for forms with the approval fields embedded), Collect must be:

- Incorrectly interpreting instance status allowing them to be submitted
- Incorrectly setting instance status, allowing incomplete forms to be marked as completed
- Doing something else that allows one of the above to happen, either by user intervention or automatically as the result of a defect

**Comment by batkinson** [comment] 2018-08-28 12:03
> unless users are able to and are in fact approving incomplete forms using the app's approval functionality (which would only work for forms with the approval fields embedded)

I checked on whether is was possible for users to use the approval functionality to cause the observed behavior. `ChecklistFragment.setupApproveAdapter(...)` only loads forms that require approval. Any form instance having a status other than "submitted" containing &lt;needsReview&gt;1&lt;/needsReview&gt; is added to the list of forms that can be approved. Notice this ***does allow*** incomplete forms to be marked as complete. Once populated, users can either 'approve all' or 'approve selected' forms, which only considers forms loaded into the adapter previously. During the approval, the `approveForms` method checks to ensure that only forms requiring approval (based on the form's `needsReview` element) can be approved. What this means is that lazy supervisors could approve forms that are invalid and cause this. The only way to prevent this would be to only allow "complete" forms to be approved. Without changing Collect to be aware of "complete" but not approved instances when considering which instances to send, the approval functionality would cease to prevent unapproved forms from being uploaded (which is the whole point of that functionality).

Based on what I have seen so far, this issue isn't limited to forms that include a `needsReview` element, so I ***do not*** think this is the issue we're seeing.

**Comment by batkinson** [comment] 2018-08-29 10:14
Looking at the Collect code, one way that a generated form instance could be imported as complete is that the application now scans the instances folder in the background. This scan registers instances in Collect's instances database and sets the status to complete or incomplete based on a user preference, instance_sync. The default value appears to be true in Collect's `InstanceSyncTask`.

**Comment by batkinson** [comment] 2018-08-31 14:55
The attached zip file
[incomplete-forms-submitted.zip](https://github.com/cims-bioko/cims-tablet/files/2340484/incomplete-forms-submitted.zip) contains the query I used to find forms that violate the basic constraints of the form design. It includes the form submissions that do not have a valid answer for the `Survey` question for the 2018 malaria indicator survey form. This question is a select1 that is required with no relevant expression. The value should be supplied, and it should be a value in the set ('1', '2'). It should not be possible to complete these questions in Collect under normal circumstances, but yet they were submitted successfully. It is worth noting that the forms do include the information injected into them by cims-tablet upon initial creation.

**Comment by mmperry** [comment] 2018-08-31 15:00
Is there an easy way to get the household data out in CSV form for Olivier?  He need the records for the final dataset.

**Comment by batkinson** [comment] 2018-09-06 10:39
I talked to Olivier Tresor, the original user reporting this issue, about what he was experiencing. My understanding from talking to him was that they were using the count of submitted forms from Collect to check against the number of houses from the CIMS as a quality check and there was a discrepancy due to these blank forms. After continuing to probe into the actual missing records, he said that he gave Megan (the reporter of this issue) a list of form instance ids that were failing. It turns out that this list matched the forms found by my query attached above *exactly* with the exception of a blank form that was submitted since (on the 1st of September). I don't know the point of the other data was in the spreadsheet above, but it seems more of a side effect of an attempt to identify the records related to this issue than evidence of the root problem. Megan: can you confirm? If this is accurate, I will have more confidence with the direction this is heading in.

**Comment by mmperry** [comment] 2018-09-06 10:57
Yes the records also match the blank records I had, just queried it differently to try and figure out the problem.

**Comment by batkinson** [comment] 2018-09-11 13:43
Without more information from the tablets that are actually creating these, I am not sure I will be able to get to the root cause with 100% certainty. However, it appears that the only way for this to happen is by cims-tablet failling to successfully register a generated form instance when Collect is configured to auto-import instances. Since it marks all instances as complete when importing without validating the form, empty forms will be marked complete as if they were filled in. Disabling the auto-import feature should prevent this from resulting in the forms being submitted, but it would be nice to see what is causing the failure as well.

**Closed by batkinson** 2018-09-11 13:43 UTC
